simplify start script

diff --git a/.github/start-server/action.yml b/.github/start-server/action.yml
--- a/.github/start-server/action.yml
+++ b/.github/start-server/action.yml
@@ -8,27 +8,19 @@ runs:
       shell: bash
       run: |
         set +o pipefail
-        yes TESTVALUE | make docker-serve ARGS="--detach"
+        yes TESTVALUE | make .env
         set -o pipefail
+        make docker-serve ARGS="--detach"
+    - name: wait for server to start
+      shell: bash
+      run: docker-compose logs -f | sed -e '/Server Started/q' -e '/Failed to start/q1'
     - name: check server is running
       shell: bash
       run: |
-        start_time=$(date +%s)
-        timeout=60
-        
-        while true; do
-          current_time=$(date +%s)
-          elapsed=$((current_time - start_time))
-          
-          response=$(curl -sS -X GET 'http://localhost:8080/system/health' -H 'accept: application/json' -o /dev/null -w "%{http_code}" --connect-timeout 2 --max-time 2 || echo "connection reset")
-          if [ "$response" = "200" ]; then
-            echo "Server is up and running"
-            exit 0
-          fi
-        
-          if [ $elapsed -ge $timeout ]; then
-            echo "Timeout reached. Server did not respond within 5 minutes."
-            exit 1
-          fi
-          sleep 1
-        done
+        code=$(curl -sS -o /dev/null -w "%{http_code}" 'http://localhost:8080/system/health')
+        echo "Server health status code: $code"
+        if [ "$code" -ne 200 ]; then
+        echo "Server health check failed"
+        exit 1
+        fi
+
