another pipefail

diff --git a/.github/start-server/action.yml b/.github/start-server/action.yml
--- a/.github/start-server/action.yml
+++ b/.github/start-server/action.yml
@@ -13,7 +13,10 @@ runs:
         make docker-serve ARGS="--detach"
     - name: wait for server to start
       shell: bash
-      run: docker compose logs -f | sed -e '/Server Started/q' -e '/Failed to start/q1'
+      run: |
+        set +o pipefail
+        docker compose logs -f | sed -e '/Server Started/q' -e '/Failed to start/q1'
+        set -o pipefail
     - name: check server is running
       shell: bash
       run: |
