use awk

diff --git a/.github/start-server/action.yml b/.github/start-server/action.yml
--- a/.github/start-server/action.yml
+++ b/.github/start-server/action.yml
@@ -13,10 +13,7 @@ runs:
         make docker-serve ARGS="--detach"
     - name: wait for server to start
       shell: bash
-      run: |
-        set +o pipefail
-        docker compose logs -f | sed -e '/Server Started/q' -e '/Failed to start/q1'
-        set -o pipefail
+      run: docker compose logs -f | awk '/Server Started/ {exit 0} /Failed to start/ {exit 1} {print}'
     - name: check server is running
       shell: bash
       run: |
